spring:
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/middleearth
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        hibernate:
            ddl-auto: update
    mail:
        host: smtp.gmail.com
        port: 587
        username: "noreply.middleearth.maps@gmail.com"
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        password: "your_actual_password"

app:
    url: http://localhost:8080/

jwt:
    secret: your_jwt_secret

dozer:
    mapping-files: classpath:mapping.xml

bearerToken: your_bearer_token

theOneBearerToken: your_the_one_bearer_token
